name: buid-maven

on:
  push:
    branches:
    - "*"
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: 17
    - name: Build with Maven
      run: mvn -B package --no-transfer-progress --file pom.xml
